# Generated by Django 3.2.13 on 2023-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesmodel',
            name='image',
            field=models.ImageField(upload_to='http://139.59.85.104/v1/storage/buckets/6446db7f0a8efb801dba/files/'),
        ),
    ]
