# Generated by Django 3.2.13 on 2023-04-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_data_podcastmodel_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
