# Generated by Django 3.2.13 on 2023-04-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_podcastmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastmodel',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='podcastmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
